# Generated by Django 3.2.13 on 2022-05-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('Comment', models.CharField(max_length=200)),
            ],
        ),
    ]
